
// ACTIONT TYPES FOR initalBody
export const ADD_RECIPE_TO_BODY = "ADD_RECIPE_TO_BODY";
export const ADD_RECIPE_CATEGORIES_TO_BODY = "ADD_RECIPE_CATEGORIES_TO_BODY";
export const ADD_TAGS_TO_BODY = "ADD_TAGS_TO_BODY";
export const ADD_RECIPE_TAGS_TO_BODY = "ADD_RECIPE_TAGS_TO_BODY";
export const ADD_IMAGES_TO_BODY = "ADD_IMAGES_TO_BODY";
export const ADD_INGREDIENTS_TO_BODY = "ADD_INGREDIENTS_TO_BODY";
export const ADD_RECIPE_INGREDIENTS_TO_BODY = "ADD_RECIPE_INGREDIENTS_TO_BODY";
export const ADD_INSTRUCTIONS_TO_BODY = "ADD_INSTRUCTIONS_TO_BODY";